#!/bin/sh
#
# UIO
#

start() {
	if [ -e /sys/class/uio/uio0/dev ] ; then
		echo "create UIO device file"
		rm -f /dev/uio0
		mknod /dev/uio0 c $(cat /sys/class/uio/uio0/dev| sed -r "s/:/ /g")
	fi
}

case "$1" in
  start)
	start
	;;
  *)
	echo $"Usage: $0 {start}"
	exit 1
esac

exit $?
