#!/bin/sh

# Only run at system boot, not at system shutdown
if [ "$1" != "start" ] ; then
  exit
fi

CHECK=`date | grep "UTC 1970"`
if [ "$CHECK" != "" ] ; then
  # Set date/time to something other than 1970
  date -s "2017-11-01 9:00:00"
fi

# unbind displaying console messages on the LCD (and blinking cursor)
if [ -e /sys/class/vtconsole/vtcon1/bind ]; then
  echo 0 > /sys/class/vtconsole/vtcon1/bind
  echo 0 > /sys/class/graphics/fbcon/cursor_blink
fi

# put splash image on LCD
if [ -e /sys/devices/platform/vdc5fb.0/graphics/fb0/bits_per_pixel ] ; then
    # only if the file exists
    if [ -e /root/images/renesas_logo-800x480.jpg ]; then
      fbv -s 1 -c -f /root/images/renesas_logo-800x480.jpg
    fi
fi

alias ll='ls -lap'
	
# set prompt
#PS1='$ '
PS1='\[\e[1;32m\]$\[\e[00m\] '

### ALSA Sound Settings ####
QUIET='-q'

# Set up ALSA sound paramters
#  'alsactl restore' pulls from /var/lib/alsa/asound.state
alsactl restore
#amixer $QUIET cset name="SSI0 Control" 1

# Set LINE out volume (Left% , Right%)
# amixer $QUIET sset 'Digital Audio Input',0 50%,50%

# Check to see if we should run any demos
# Only checks sda1 (first partition of a USB drive)
SDA1_EXIST=$(cat /proc/partitions | grep sda1)

if [ "$SDA1_EXIST" != "" ] ; then

  if [ ! -e /mnt/sda1 ] ; then
    mkdir /mnt/sda1
  fi
 
  mount /dev/sda1 /mnt/sda1

  if [ -e /mnt/sda1/autorun.txt ] ; then
    source /mnt/sda1/autorun.txt
  fi

  #umount /mnt/sda1

fi


